apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-helloworld
  labels:
    app: php-helloworld
spec:
  replicas: 4
  selector:
    matchLabels:
      project: php-helloworld
  template:
    metadata:
      labels:
        project: php-helloworld
    spec:
      containers:
        - name: php-helloworld
          image: ghcr.io/execut/php-helloworld
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-container-registry