apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-helloworld
  labels:
    app:
      php-helloworld
spec:
  selector:
    matchLabels:
      project: php-helloworld
  template:
    spec:
      containers:
        - name: php-helloworld
          image: ghcr.io/execut/php-helloworld
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-container-registry