apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-helloworld
  labels:
    app:
      php-helloworld
spec:
  template:
    spec:
      containers:
        - name: php-helloworld
          image: ghcr.io/execut/php-helloworld
      imagePullSecrets:
        - name: github-container-registry