name: Deploy
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  Publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and tag image
        run: |
          docker build -t execut/php-helloworld" .

      - name: Run tests
        run: docker run execut/php-helloworld ./test

      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        run: docker push "docker.pkg.github.com/execut/php-helloworld"
  Deploy-image:
    runs-on: ubuntu-latest
    name: 'Deploy on the production server'
    steps:

      - uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: 'ssh://${{ secrets.USERNAME }}@${{ secrets.HOST }}'
          context_name: 'prod-server'
          ssh_cert: ${{ secrets.SSH_PRIV_KEY }}
          ssh_key: ${{ secrets.SSH_PUB_KEY }}

      - run: |
          docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
          docker --context prod-server -dp 8001:80 execut/php-helloworld