name: Deploy
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and tag image
      run: |
        docker build . -t ghcr.io/execut/php-helloworld:latest

    - name: Run tests
      run: docker run ghcr.io/execut/php-helloworld:latest ./test

    - name: Docker login
      run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

    - name: Publish image
      run: docker push ghcr.io/execut/php-helloworld:latest


    - name: Deploy on production server via Docker
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: docker login ghcr.io -u ${{github.actor}} -p ${{secrets.GH_TOKEN}} && docker stop php-helloworld && docker run --rm -d --pull always -p 8001:80 --name php-helloworld ghcr.io/execut/php-helloworld:latest
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.SSH_PRIV_KEY}}