name: Deploy easy level
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . -t ghcr.io/execut/php-helloworld:${{ github.sha }}

      - name: Run tests
        run: docker run ghcr.io/execut/php-helloworld:${{ github.sha }} ./test

      - name: Docker login
        run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        run: docker push ghcr.io/execut/php-helloworld:${{ github.sha }}

      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            docker login ghcr.io -u ${{github.actor}} -p ${{secrets.GH_TOKEN}} &&
            docker stop php-helloworld || true &&
            docker run --rm -d --pull always -p 8001:80 --name php-helloworld ghcr.io/execut/php-helloworld:${{ github.sha }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_PRIV_KEY}}