name: Deploy middle level
on:
  workflow_run:
    workflows: [Publish image]
    types:
      - completed
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          docker login ghcr.io -u ${{github.actor}} -p ${{secrets.GH_TOKEN}} &&
          docker stop php-helloworld &&
          docker run --rm -d --pull always -p 8001:80 --name php-helloworld ghcr.io/execut/php-helloworld:${{ github.sha }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.SSH_PRIV_KEY}}