name: Deploy
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  Publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and tag image
        run: |
          docker build . -t ghcr.io/execut/php-helloworld:latest

      - name: Run tests
        run: docker run ghcr.io/execut/php-helloworld:latest ./test

      - name: Docker login
        run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        run: docker push ghcr.io/execut/php-helloworld:latest

      - name: Deploy on production server
        uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: ${{ format('ssh://{0}@{1}', secrets.USERNAME, secrets.HOST) }}
          context_name: 'prod-server'
          ssh_cert: ${{ secrets.SSH_PUB_KEY }}
          ssh_key: ${{ secrets.SSH_PRIV_KEY }}

      - run: docker --context prod-server login ghcr.io -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}} && docker --context prod-server run -dp 8001:80 ghcr.io/execut/php-helloworld:latest