name: Deploy hard level
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-hub/kubectl@master
        env:
          KUBE_HOST: ${{ secrets.HOST }}
          KUBE_USERNAME: ${{ secrets.KUBE_USERNAME }}
          KUBE_PASSWORD: ${{ secrets.KUBE_PASSWORD }}
        with:
          args: get pods