name: Deploy hard level
on:
  workflow_run:
    workflows: [Publish image]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBE_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v4.3
        with:
          namespace: default
          manifests: k8s/deployment.yaml
          images: |
            ghcr.io/execut/php-helloworld:${{ github.sha }}