name: Deploy easy level
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1

    - name: Run tests
      run: ./test

    - name: Deploy
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd /var/www/hello-world && git pull
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.SSH_PRIV_KEY}}