name: Publish image
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build image
      run: docker build . -t ghcr.io/execut/php-helloworld:${{ github.sha }}

    - name: Run tests
      run: docker run ghcr.io/execut/php-helloworld:${{ github.sha }} ./test

    - name: Docker login
      run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

    - name: Publish image
      run: docker push ghcr.io/execut/php-helloworld:${{ github.sha }}